repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
# -   repo: https://github.com/pre-commit/mirrors-scss-lint
#     rev: v0.57.1-1
#     hooks:
#     -   id: scss-lint
# -   repo: https://github.com/pre-commit/mirrors-ruby-lint
#     rev: v2.3.1-1
#     hooks:
#     -   id: ruby-lint
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.9.7
    hooks:
    -   id: jshint

  # Disable dotnet-format until https://github.com/dotnet/sdk/issues/39723 is resolved.

  # Check C# code formatting with dotnet-format
  # - repo: https://github.com/dotnet/format
  #   rev: v8.0.453106
  #   hooks:
  #     - id: dotnet-format

  # Check C# code formatting with clang-format
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.5
    hooks:
      - id: clang-format
        types: [c#]
