repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test

  #--------------
  # Check Python
  #--------------
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8

  #----------
  # Check C# 
  #----------

  # Disable dotnet-format until https://github.com/dotnet/sdk/issues/39723 is resolved.

  # Check C# code formatting with dotnet-format
  # - repo: https://github.com/dotnet/format
  #   rev: v8.0.453106
  #   hooks:
  #     - id: dotnet-format

  # TODO Find a C# linter hook that uses .editorconfig

  #-------------
  # Check C/C++ 
  #-------------
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.5
    hooks:
      - id: clang-format
        types_or: [c,c++,c#]

-   repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
      - id: cpplint
        args: ['--quiet']

  #---------------------
  # Check Shell Scripts
  #---------------------
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  #------------------------
  # Check GitHub workflows
  #------------------------
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint

  #--------------------------------------
  # Check for exposed passwords and keys
  #--------------------------------------
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.2
    hooks:
      - id: gitleaks
